#pragma once
#ifndef RODZAJCZASULOKATY_H
#define RODZAJCZASULOKATY_H

enum RodzajCzasuLokaty {
	RODZAJ_CZASU_LOKATA_3MIESIECZNA = 0,
	RODZAJ_CZASU_LOKATA_6MIESIECZNA = 1,
	RODZAJ_CZASU_LOKATA_12MIESIECZNA = 2,
	BRAK = 3
};

#endif // !RODZAJCZASULOKATY_H